version: "3.11"

services:
  assignment1-demo:
    build: .
    command: python -m assignment1.producer_consumer

  assignment2-report:
    build: .
    command: python -m assignment2.main

  tests:
    build: .
    command: python -m pytest --cov=. --cov-report=term --cov-fail-under=80
